export const CLEAR_CHILD_STORE = 'CLEAR_CHILD_STORE';

export const CREATE_CHILD_START = 'CREATE_CHILD_START';
export const CREATE_CHILD_END = 'CREATE_CHILD_END';
export const CREATE_CHILD_SUCCESS = 'CREATE_CHILD_SUCCESS';
export const CREATE_CHILD_FAILURE = 'CREATE_CHILD_FAILURE';

export const GET_CHILDREN_START = 'GET_CHILDREN_START';
export const GET_CHILDREN_END = 'GET_CHILDREN_END';
export const GET_CHILDREN_SUCCESS = 'GET_CHILDREN_SUCCESS';
export const GET_CHILDREN_FAILURE = 'GET_CHILDREN_FAILURE';

export const GET_VACCINATED_CHILDREN_START = 'GET_VACCINATED_CHILDREN_START';
export const GET_VACCINATED_CHILDREN_END = 'GET_VACCINATED_CHILDREN_END';
export const GET_VACCINATED_CHILDREN_SUCCESS = 'GET_VACCINATED_CHILDREN_SUCCESS';
export const GET_VACCINATED_CHILDREN_FAILURE = 'GET_VACCINATED_CHILDREN_FAILURE';