export const CLEAR_CHILD_STORE = 'CLEAR_CHILD_STORE';

export const CREATE_CHILD_START = 'CREATE_CHILD_START';
export const CREATE_CHILD_END = 'CREATE_CHILD_END';
export const CREATE_CHILD_SUCCESS = 'CREATE_CHILD_SUCCESS';
export const CREATE_CHILD_FAILURE = 'CREATE_CHILD_FAILURE';