export const CLEAR_HOSPITAL_STORE = 'CLEAR_HOSPITAL_STORE';

export const SIGNUP_HOSPITAL_START = 'SIGNUP_HOSPITAL_START';
export const SIGNUP_HOSPITAL_END = 'SIGNUP_HOSPITAL_END';
export const SIGNUP_HOSPITAL_SUCCESS = 'SIGNUP_HOSPITAL_SUCCESS';
export const SIGNUP_HOSPITAL_FAILURE = 'SIGNUP_HOSPITAL_FAILURE';