export const CLEAR_PARENT_STORE = 'CLEAR_PARENT_STORE';

export const CREATE_PARENT_START = 'CREATE_PARENT_START';
export const CREATE_PARENT_END = 'CREATE_PARENT_END';
export const CREATE_PARENT_SUCCESS = 'CREATE_PARENT_SUCCESS';
export const CREATE_PARENT_FAILURE = 'CREATE_PARENT_FAILURE';