export const CLEAR_PARENT_STORE = 'CLEAR_PARENT_STORE';

export const CREATE_PARENT_START = 'CREATE_PARENT_START';
export const CREATE_PARENT_END = 'CREATE_PARENT_END';
export const CREATE_PARENT_SUCCESS = 'CREATE_PARENT_SUCCESS';
export const CREATE_PARENT_FAILURE = 'CREATE_PARENT_FAILURE';

export const GET_PARENTS_START = 'GET_PARENTS_START';
export const GET_PARENTS_END = 'GET_PARENTS_END';
export const GET_PARENTS_SUCCESS = 'GET_PARENTS_SUCCESS';
export const GET_PARENTS_FAILURE = 'GET_PARENTS_FAILURE';