export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';

export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_END = 'CREATE_USER_END';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';