export const CLEAR_VACCIN_STORE = 'CLEAR_VACCIN_STORE';

export const CREATE_VACCIN_START = 'CREATE_VACCIN_START';
export const CREATE_VACCIN_END = 'CREATE_VACCIN_END';
export const CREATE_VACCIN_SUCCESS = 'CREATE_VACCIN_SUCCESS';
export const CREATE_VACCIN_FAILURE = 'CREATE_VACCIN_FAILURE';