export const CLEAR_VACCIN_STORE = 'CLEAR_VACCIN_STORE';

export const CREATE_VACCIN_START = 'CREATE_VACCIN_START';
export const CREATE_VACCIN_END = 'CREATE_VACCIN_END';
export const CREATE_VACCIN_SUCCESS = 'CREATE_VACCIN_SUCCESS';
export const CREATE_VACCIN_FAILURE = 'CREATE_VACCIN_FAILURE';

export const GET_VACCINES_START = 'GET_VACCINES_START';
export const GET_VACCINES_END = 'GET_VACCINES_END';
export const GET_VACCINES_SUCCESS = 'GET_VACCINES_SUCCESS';
export const GET_VACCINES_FAILURE = 'GET_VACCINES_FAILURE';